TwilioProject/TwilioProject/Models/EventUsers.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace TwilioProject.Models
{
    public class EventUsers
    {
        [Key]
        public string UserID { get; set; }
        [Display(Name = "Phone Number")]
        public string PhoneNumber { get; set; }
        [ForeignKey("Events")]
        public int? EventID { get; set; }
        public Events Events { get; set; }
        public bool? isBanned { get; set; }
        public string Id1 { get; set; }
        public string Id2 { get; set; }
        public string Id3 { get; set; }
        public string Id4 { get; set; }
        public string Id5 { get; set; }
        public string Title1 { get; set; }
        public string Title2 { get; set; }
        public string Title3 { get; set; }
        public string Title4 { get; set; }
        public string Title5 { get; set; }
        [ForeignKey("ApplicationUser")]
        public string AppUserId { get; set; }
        public ApplicationUser ApplicationUser { get; set; }

    }
}

TwilioProject/TwilioProject/Controllers/EventUsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TwilioProject.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;

namespace TwilioProject.Controllers
{
    public class EventUsersController : Controller
    {
        ApplicationDbContext db = new ApplicationDbContext();

        // GET: EventUsers
        public ActionResult Index()
        {
            return View();
        }

        // GET: Host Controller
        public ActionResult IndexHost()
        {

            var user = User.Identity.GetUserId();
            
            var requiredEventData =
                (from x in db.Events
                 where x.HostID == user
                 select x).FirstOrDefault();
            var myEvent =
                (from x in db.Events
                 where x.IsHosted == true
                 select x).FirstOrDefault();

            var isActiveEvent = (requiredEventData != null) ? true : false;
            if (isActiveEvent)
            {
                var eventCode = (requiredEventData.IsHosted == true) ? requiredEventData.EventCode : null;
                if (eventCode != null)
                {
                    ViewBag.EventCode = null;
                    ViewBag.EventCode = myEvent.EventCode;
                }
            }
            else
            {
                ViewBag.EventCode = "There is no current event";
            }
            return View();
        }
        [ChildActionOnly]
        public ActionResult QueueList()
        {
            var x = db.Playlist.Select(y => y.SongOrderID).ToArray();
            Array.Sort(x);
            List<Playlist> queue = new List<Playlist>();
            for(int i = 0; i < x.Count(); i++)
            {
                var songOrderID = x[i];
                var newItem = db.Playlist.Where(y => y.SongOrderID == songOrderID).Select(y => y).FirstOrDefault();

                queue.Add(newItem);
            }
            ViewBag.Queue = queue;
            return PartialView();
        }
        [ChildActionOnly]
        public ActionResult PopularList()
        {

            var y = db.Songs.OrderByDescending(x => x.Likes).Take(5).Select(x => x).ToList();
            ViewBag.TopList = y;
            return PartialView();

        }
        public ActionResult AttendeeIndex()
        {
            return View();
        }

        //
        // GET: Host Creat
        public ActionResult CreateHost()
        {
            return View();
        }
        //
        // POST: Host Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateHost(EventUsers model)
        {
            var user = User.Identity.GetUserId();
            var newID = new Guid().ToString();
            var newHost = new EventUsers { PhoneNumber = model.PhoneNumber, AppUserId = user, UserID = user };
            db.EventUsers.Add(newHost);
            db.SaveChanges();
            return RedirectToAction("IndexHost");
        }
        
        //GET: AttendeeSongRequest
        public ActionResult _PartialAttendeeSongRequest()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        //POST: AttendeeSongRequest
        public ActionResult _PartialAttendeeSongRequest(Songs song)
        {
            YoutubeSearch songSearch = new YoutubeSearch();
            var searchResults = songSearch.SearchByTitle(song.Title);
            List<string> songList = new List<string>();
            for (var i = 0; i < searchResults.Count; i++)
            {
                string result = searchResults[i][0];
                songList.Add(result);
            }
            Playlist model = new Playlist();
            model.Title = song.Title;
            ViewBag.SongList = songList;
            return View("SongSearchResults");
        }

        //
        // Get Banned Song
        [ChildActionOnly]
        public ActionResult ManageBannedSongs()
        {
            var zz = db.Songs.Where(m => m.IsBanned == true).Select(m => m.Title).ToList();
            ViewBag.BannedList = zz;
            
            return PartialView();
        }
        // Post Banned Song
        [HttpPost]
        public ActionResult ManageBannedSOngs(Playlist toBan)
        {
            Songs newSong = new Songs();
            newSong.YoutubeId = toBan.YoutubeID;
            newSong.IsBanned = true;
            return RedirectToAction("IndexHost");
        }


        //GET: display top 5 search results to attendee
        public ActionResult SongSearchResults()
        {
            return View();
        }
        //POST: queue the attendees final selection
//GET: adds attendees song to the playlist

        public ActionResult SearchResult(string Title)
        {
            var user = User.Identity.GetUserId();
            var w =
                (from q in db.EventUsers
                 where q.AppUserId == user
                 select q).FirstOrDefault();

            YoutubeSearch songSearch = new YoutubeSearch();
            var searchResults = songSearch.SearchByTitle(Title);

                var selectedSong = searchResults.Select(x => searchResults[0]).First();
                Playlist song = new Playlist();
                song.Title = selectedSong[0];
                song.YoutubeID = selectedSong[1];
                song.PhoneNumber = w.PhoneNumber;
                db.Playlist.Add(song);
                db.SaveChanges();

            return View("AttendeeIndex");
        }
    }
}

TwilioProject/TwilioProject/Views/EventUsers/AttendeeIndex.cshtml
@{
    ViewBag.Title = "AttendeeIndex";
}

@Html.Partial("_PartialAttendeeSongRequest")


<div class="row whitespace-remove">
    <div class=" whitespace-remove">
        <div class="whitespace-remove text-primary">
            <center>
                <h2>Attendee</h2>
            </center>
        </div>
    </div>
</div>

@Html.Action("QueueList")
@Html.Action("PopularList")

@*<div class="container bg-primary">
        <div class="row">
            <div class="col-md-6 pull-left">
                <h4 class="d-flex" id="songTitle">ViewBag.Title</h4>
            </div>
            <div class="col-md-3 pull-right">
                <button class="btn btn-sm likeOrDislikeButtons">Dislike</button>
            </div>
            <div class="col-md-3 pull-right">
                <button class="btn btn-sm likeOrDislikeButtons">Like</button>
            </div>
        </div>
    </div>*@

TwilioProject/TwilioProject/Views/EventUsers/CreateHost.cshtml
@model TwilioProject.Models.EventUsers
@{
    ViewBag.Title = "CreateHost";
}

<a href="#" class="btn btn-primary btn-block btn-lg landing-btn" role="button" aria-disabled="false" data-toggle="modal" data-target="#modalCreateHost">Create Host</a>

<div class="modal fade" id="modalCreateHost" tabindex="-1" role="dialog" aria-labelledby="modalCreateHost" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header text-center">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title w-100 font-weight-bold">Add Account Information</h4>

            </div>
            <div class="modal-body d-flex justify-content-center">

                @using (Html.BeginForm("CreateHost", "EventUsers", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
                {
                    @Html.AntiForgeryToken()
                    <center><h4>Create a new account.</h4></center>
                    <hr />
                    @Html.ValidationSummary("", new { @class = "text-danger" })
                    <div class="form-group">
                        @Html.LabelFor(m => m.PhoneNumber, new { @class = "col-md-2 control-label" })
                        <div class="col-md-10">
                            @Html.TextBoxFor(m => m.PhoneNumber, new { @class = "form-control" })
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" class="btn btn-primary btn-block" value="Enter Account Information" />
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

TwilioProject/TwilioProject/Views/EventUsers/IndexHost.cshtml
@{
    ViewBag.Title = "IndexHost";
}
<div class="container whitespace-remove" id="host-index-container">
    <div class="row whitespace-remove" id="hostJumbotron">
        <div class="jumbotron jumbotron-fluid whitespace-remove">
            <div class="container" id="hostJumboTronContent">
                <center>
                    <h3>Current Event Code</h3>
                    <h1>@ViewBag.EventCode</h1>
                </center>
            </div>
        </div>
    </div>
    <div class="row whitespace-remove">
        <div class=" whitespace-remove">
            <div class="collapse" id="eventMenu">
                <div class="bg-primary p-4 whitespace-remove">
                    @Html.Partial("~/Views/Event/CreateEvent.cshtml")
                    @Html.Partial("~/Views/Event/_PartialManageEvent.cshtml")
                </div>
            </div>
            <nav class="whitespace-remove">
                <button class="btn btn-primary btn-block btn-lg navbar-toggler test" type="button" data-toggle="collapse" data-target="#eventMenu" aria-controls="navbarToggleExternalContent" aria-expanded="false" aria-label="Toggle navigation">
                    My Events Manager
                </button>
            </nav>
        </div>
        <div class="pos-f-t whitespace-remove">
            <div class="collapse whitespace-remove" id="playlistMenu">
                <div class="bg-primary p-4 whitespace-remove">
                    @*<button class="btn btn-primary btn-block btn-lg" type="button">Set Playlist</button>*@
                    @*<a href="#" class="btn btn-primary btn-block btn-lg" role="button" aria-disabled="false" data-toggle="modal" data-target="#modalSetPlaylistForm">Set Playlist</a>*@
                    @Html.Action("QueueList", "EventUsers")
                    @Html.Action("PopularList", "EventUsers")
                    @Html.Action("ManageBannedSongs")
                </div>
            </div>
            <nav class="whitespace-remove">
                <button class="btn btn-info btn-block btn-lg navbar-toggler test" type="button" data-toggle="collapse" data-target="#playlistMenu" aria-controls="navbarToggleExternalContent" aria-expanded="false" aria-label="Toggle navigation">
                    My Music
                </button>
            </nav>
        </div>
    </div>
</div>

@* Create Event Modal *@
<div class="modal fade" id="modalCreateEventForm" tabindex="-1" role="dialog" aria-labelledby="myCreateEventModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header text-center">
                <h4 class="modal-title w-100 font-weight-bold">Create Event</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body mx-3">
                <div class="md-form mb-5">
                    <i class="fa fa-envelope prefix grey-text"></i>
                    <input type="text" id="defaultForm-CreateEvent" class="form-control validate">
                    <label data-error="wrong" data-success="right" for="defaultForm-CreateEvent">Event Name</label>
                </div>
            </div>
            <div class="modal-footer d-flex justify-content-center">
                <button class="btn btn-default">Create Event</button>
            </div>
        </div>
    </div>
</div>
@* Past Event Modal *@
<div class="modal fade" id="modalPastEventForm" tabindex="-1" role="dialog" aria-labelledby="myPastEventModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header text-center">
                <h4 class="modal-title w-100 font-weight-bold">View Past Events</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body mx-3">
                @*@using (Html.BeginForm())
                {
                   
                        @Html.DropDownList("sudo")
                    
                }*@
            </div>
            <div class="modal-footer d-flex justify-content-center">
                <button class="btn btn-default">View Event Info</button>
            </div>
        </div>
    </div>
</div>
@* Set Playlist Modal *@
<div class="modal fade" id="modalSetPlaylistForm" tabindex="-1" role="dialog" aria-labelledby="modalSetPlaylistForm" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header text-center">
                <h4 class="modal-title w-100 font-weight-bold">Set Playlist</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body mx-3">
                @*@using (Html.BeginForm())
                {

                    @Html.DropDownList("sudo")

                }*@
            </div>
            <div class="modal-footer d-flex justify-content-center">
                <button class="btn btn-default">Submit</button>
            </div>
        </div>
    </div>
</div>

TwilioProject/TwilioProject/Views/EventUsers/ManageBannedSongs.cshtml
@model TwilioProject.Models.Playlist
@{
    ViewBag.Title = "ManageBannedSongs";
}
<a href="#" class="btn btn-info btn-block btn-lg" role="button" aria-disabled="false" data-toggle="modal" data-target="#modalManageBannedSongs" style="color: white">Manage Banned Songs</a>

<div class="modal fade" id="modalManageBannedSongs" tabindex="-1" role="dialog" aria-labelledby="modalManageBannedSongs" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header text-center">
                <h4 class="modal-title w-100 font-weight-bold" style="color:black">Manage Banned Songs</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body mx-3">
        
                    <table class="table" >
                        <tr>
                            <th style="color:black">Song Title</th>
                        </tr>
                        @foreach (var item in ViewBag.BannedList)
                        {
                            <tr>
                                <td style="color:black">@Html.DisplayTextFor(m => item)</td>
                            </tr>
                        }
                    </table>
            </div>
        </div>
    </div>
</div>

TwilioProject/TwilioProject/Views/EventUsers/PopularList.cshtml
<a href="#" class="btn btn-primary btn-block btn-lg" role="button" aria-disabled="false" data-toggle="modal" data-target="#modalViewPopularList">View Popular Songs</a>

<div class="modal fade" id="modalViewPopularList" tabindex="-1" role="dialog" aria-labelledby="modalViewPopularList" aria-hidden="true" style="color: black">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header text-center">
                <h4 class="modal-title w-100 font-weight-bold">Popular Songs</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body mx-3">

                <ul class="list-group">
                        @foreach (var item in ViewBag.TopList)
                        {
                            <li class="list-group-item">@item.Title</li>
                        }
                    </ul>

            </div>
        </div>
    </div>
</div>

TwilioProject/TwilioProject/Views/EventUsers/QueueList.cshtml
<a href="#" class="btn btn-info btn-block btn-lg" role="button" aria-disabled="false" data-toggle="modal" data-target="#modalViewQueueList">View Queue</a>

<div class="modal fade" id="modalViewQueueList" tabindex="-1" role="dialog" aria-labelledby="modalViewQueueList" aria-hidden="true" style="color:black">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header text-center">
                <h4 class="modal-title w-100 font-weight-bold">Event Queue</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body mx-3">
                @* UNCOMMENT BEFORE DEPLOYMENT, ALSO DELETE THIS COMMENT BEFORE SUBMISSION *@
                    <ul class="list-group">
                        @{ 
                            var counter = 1;
                        }
                        @foreach (var item in ViewBag.Queue)
                        {
                            <li class="list-group-item">@counter | @item.Title</li>
                            counter++;
                        }
                    </ul>

            </div>
        </div>
    </div>
</div>

TwilioProject/TwilioProject/Views/EventUsers/SongSearchResults.cshtml
@model TwilioProject.Models.Playlist
@{
    ViewBag.Title = "SongSearchResults";
}




<table class="table">
    <tr>
        <th>
            <div class="row whitespace-remove">
                <div class=" whitespace-remove">
                    <div class="whitespace-remove text-primary bg-primary">
                        <center>
                            <h2>Select Song</h2>
                        </center>
                    </div>
                </div>
            </div>
        </th>

    </tr>

    @foreach (var item in ViewBag.SongList)
    {
        <tr>
            <td>
                @Html.DisplayTextFor(m => item);
            </td>
            <td>
                 @Html.ActionLink("Select", "SearchResult", new { title = item })
            </td>
        </tr>
    }

</table>

TwilioProject/TwilioProject/Views/EventUsers/_PartialAttendeeSongRequest.cshtml
@model TwilioProject.Models.Songs
@{
    ViewBag.Title = "_PartialAttendeeSongRequest";
}

<div class="container whitespace-remove" id="host-index-container">
    <div class="row whitespace-remove" id="attendeeJumbotron">
        <div class="jumbotron jumbotron-fluid whitespace-remove">
            <div class="container" id="attendeeJumboTronContent">
                <center>
                    <h2>Queue a Song</h2>
                    <a href="#" id="songSearchButton" class="btn btn-lg" role="button" aria-disabled="false" data-toggle="modal" data-target="#songSearch">Search For a Song</a>
                </center>
            </div>
        </div>
    </div>
    <div class="modal fade" id="songSearch" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header text-center">
                    <h4 class="modal-title w-100 font-weight-bold">Search For a Song</h4>
                    @using (Html.BeginForm("_PartialAttendeeSongRequest", "EventUsers", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
                    {
                        @Html.AntiForgeryToken()
                        <center><h4>Search Youtube</h4></center>
                        <hr />
                        @Html.ValidationSummary("", new { @class = "text-danger" })
                        <div class="form-group">
                            @Html.LabelFor(m => m.Title, new { @class = "col-md-2 control-label" })
                            <div class="col-md-10">
                                @Html.TextBoxFor(m => m.Title, new { @class = "form-control" })
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <input type="submit" class="btn btn-primary btn-block" value="Search" />
                            </div>
                        </div>
                    }
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>              
            </div>          
        </div>       
    </div>   
 </div>